name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Update pip
        run: python -m pip install -U pip
      
      - name: Set up environment
        run: |
          pip install pytest pytest-cov
          pip install .
      
      - name: Run tests with coverage
        run: pytest -v ./tests --cov=respread --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
          verbose: true
