name: Docs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install sphinx pydata-sphinx-theme sphinx-copybutton sphinx_design
          pip install .
      - name: Sphinx build
        run: |
          sphinx-build -b html docs docs/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true